### ISSUE TITLE
Conflict with folded plugin

### ISSUE THREAD

**Issue by fletchjoyce** [turnermm/Updatable-Snippets-for-Dokuwiki#6] opened 2015-07-14 12:53 UTC
When the folded plugin is enabled the popup window in the editor doesn't work properly. I have tried clearing cache etc but so far only resolution is to disable folded.

**Comment by turnermm** [comment] 2015-07-14 13:30
1. Describe your problem. 
2. See if the  problem occurs with the [original snippets plugin](https://github.com/cosmocode/dokuwiki-plugin-snippets/tarball/master)

**Comment by fletchjoyce** [comment] 2015-07-14 13:34
1. When I click insert template in the editor the page that comes up is missing the buttons to insert
   ![image](https://cloud.githubusercontent.com/assets/13332816/8674338/ecb06892-2a6f-11e5-899a-948d73255189.png)
2. Yes this happens with the original snippets plugin

**Comment by turnermm** [comment] 2015-07-14 13:57
I inherited the original plugin and as far as I can see, it is just a standard pop-up.  So, the problem is probably on the other side, coming from the folded plugin.  You could try originating an issue with the folded plugin, and I will see what I can do from the snippets side.  But I don't use the folded plugin and so it will take some time to try it out and see what's happening.

**Comment by turnermm** [comment] 2015-07-14 19:05
I've committed a pull request with correction to the authors of folded plugin.  In the meantime, you can download my forked copy with the correction: https://github.com/turnermm/plugin-folded/archive/master.zip

**Comment by turnermm** [comment] 2016-01-25 16:10
This turned out to be fixable from within the snippets plugin itself and that has been done.

**Closed as completed by turnermm** 2016-01-25 16:10 UTC
